define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.internalZoomFactorChange = 'internalZoomFactorChange';
    exports.contentChangeEvent = 'contentChange';
    exports.documentChangeEvent = 'documentChange';
    exports.selectionChangeEvent = 'selectionChange';
    exports.zoomFactorChangeEvent = 'zoomFactorChange';
    exports.beforeFieldFillEvent = 'beforeFieldFill';
    exports.afterFieldFillEvent = 'afterFieldFill';
    exports.afterFormFieldFillEvent = 'afterFormFieldFill';
    exports.beforeFormFieldFillEvent = 'beforeFormFieldFill';
    exports.serviceFailureEvent = 'serviceFailure';
    exports.viewChangeEvent = 'viewChange';
    exports.customContextMenuSelectEvent = 'customContextMenuSelect';
    exports.customContextMenuBeforeOpenEvent = 'customContextMenuBeforeOpen';
    exports.contentControlEvent = 'contentControl';
    exports.commentBeginEvent = 'commentBegin';
    exports.commentEndEvent = 'commentEnd';
    exports.beforeCommentActionEvent = 'beforeCommentAction';
    exports.commentDeleteEvent = 'commentDelete';
    exports.revisionActionEvent = 'beforeAcceptRejectChanges';
    exports.beforePaneSwitchEvent = 'beforePaneSwitch';
    exports.requestNavigateEvent = 'requestNavigate';
    exports.actionCompleteEvent = 'actionComplete';
    exports.trackChangeEvent = 'trackChange';
    exports.searchResultsChangeEvent = 'searchResultsChange';
    exports.keyDownEvent = 'keyDown';
    exports.toolbarClickEvent = 'toolbarClick';
    exports.beforeFileOpenEvent = 'beforeFileOpen';
    exports.internalviewChangeEvent = 'internalviewChange';
    exports.beforeXmlHttpRequestSend = 'beforeXmlHttpRequestSend';
    exports.protectionTypeChangeEvent = 'protectionTypeChange';
    exports.internalDocumentEditorSettingsChange = 'internalDocumentEditorSettingsChange';
    exports.internalStyleCollectionChange = 'internalStyleCollectionChange';
    exports.defaultFont = 'Times New Roman';
    exports.internalAutoResize = 'internalAutoResize';
    exports.beforeAutoResize = 'beforeAutoResize';
    exports.trackChanges = 'trackChanges';
});
