define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    var CharacterRangeType;
    (function (CharacterRangeType) {
        CharacterRangeType[CharacterRangeType["LeftToRight"] = 0] = "LeftToRight";
        CharacterRangeType[CharacterRangeType["RightToLeft"] = 1] = "RightToLeft";
        CharacterRangeType[CharacterRangeType["WordSplit"] = 2] = "WordSplit";
        CharacterRangeType[CharacterRangeType["Number"] = 4] = "Number";
        CharacterRangeType[CharacterRangeType["Tab"] = 6] = "Tab";
    })(CharacterRangeType = exports.CharacterRangeType || (exports.CharacterRangeType = {}));
    var FontScriptType;
    (function (FontScriptType) {
        FontScriptType[FontScriptType["English"] = 0] = "English";
        FontScriptType[FontScriptType["Hindi"] = 1] = "Hindi";
        FontScriptType[FontScriptType["Korean"] = 2] = "Korean";
        FontScriptType[FontScriptType["Chinese"] = 3] = "Chinese";
        FontScriptType[FontScriptType["Arabic"] = 4] = "Arabic";
        FontScriptType[FontScriptType["Hebrew"] = 5] = "Hebrew";
        FontScriptType[FontScriptType["Japanese"] = 6] = "Japanese";
        FontScriptType[FontScriptType["Thai"] = 7] = "Thai";
    })(FontScriptType = exports.FontScriptType || (exports.FontScriptType = {}));
    var FontHintType;
    (function (FontHintType) {
        FontHintType[FontHintType["Default"] = 0] = "Default";
        FontHintType[FontHintType["EastAsia"] = 1] = "EastAsia";
        FontHintType[FontHintType["CS"] = 2] = "CS";
    })(FontHintType = exports.FontHintType || (exports.FontHintType = {}));
    var LocaleId;
    (function (LocaleId) {
        LocaleId[LocaleId["af_ZA"] = 1078] = "af_ZA";
        LocaleId[LocaleId["sq_AL"] = 1052] = "sq_AL";
        LocaleId[LocaleId["am_ET"] = 1118] = "am_ET";
        LocaleId[LocaleId["gsw_FR"] = 1156] = "gsw_FR";
        LocaleId[LocaleId["ar_DZ"] = 5121] = "ar_DZ";
        LocaleId[LocaleId["ar_BH"] = 15361] = "ar_BH";
        LocaleId[LocaleId["ar_EG"] = 3073] = "ar_EG";
        LocaleId[LocaleId["ar_IQ"] = 2049] = "ar_IQ";
        LocaleId[LocaleId["ar_JO"] = 11265] = "ar_JO";
        LocaleId[LocaleId["ar_KW"] = 13313] = "ar_KW";
        LocaleId[LocaleId["ar_LB"] = 12289] = "ar_LB";
        LocaleId[LocaleId["ar_LY"] = 4097] = "ar_LY";
        LocaleId[LocaleId["ar_MA"] = 6145] = "ar_MA";
        LocaleId[LocaleId["ar_OM"] = 8193] = "ar_OM";
        LocaleId[LocaleId["ar_QA"] = 16385] = "ar_QA";
        LocaleId[LocaleId["ar_SA"] = 1025] = "ar_SA";
        LocaleId[LocaleId["ar_SY"] = 10241] = "ar_SY";
        LocaleId[LocaleId["ar_TN"] = 7169] = "ar_TN";
        LocaleId[LocaleId["ar_AE"] = 14337] = "ar_AE";
        LocaleId[LocaleId["ar_YE"] = 9217] = "ar_YE";
        LocaleId[LocaleId["hy_AM"] = 1067] = "hy_AM";
        LocaleId[LocaleId["as_IN"] = 1101] = "as_IN";
        LocaleId[LocaleId["az_Cyrl_AZ"] = 2092] = "az_Cyrl_AZ";
        LocaleId[LocaleId["az_Latn_AZ"] = 1068] = "az_Latn_AZ";
        LocaleId[LocaleId["ba_RU"] = 1133] = "ba_RU";
        LocaleId[LocaleId["eu_ES"] = 1069] = "eu_ES";
        LocaleId[LocaleId["be_BY"] = 1059] = "be_BY";
        LocaleId[LocaleId["bn_BD"] = 2117] = "bn_BD";
        LocaleId[LocaleId["bn_IN"] = 1093] = "bn_IN";
        LocaleId[LocaleId["bs_Cyrl_BA"] = 8218] = "bs_Cyrl_BA";
        LocaleId[LocaleId["bs_Latn_BA"] = 5146] = "bs_Latn_BA";
        LocaleId[LocaleId["bg_BG"] = 1026] = "bg_BG";
        LocaleId[LocaleId["br_FR"] = 1150] = "br_FR";
        LocaleId[LocaleId["my_MM"] = 1109] = "my_MM";
        LocaleId[LocaleId["ca_ES"] = 1027] = "ca_ES";
        LocaleId[LocaleId["chr_US"] = 1116] = "chr_US";
        LocaleId[LocaleId["zh_HK"] = 3076] = "zh_HK";
        LocaleId[LocaleId["zh_MO"] = 5124] = "zh_MO";
        LocaleId[LocaleId["zh_CN"] = 2052] = "zh_CN";
        LocaleId[LocaleId["zh_SG"] = 4100] = "zh_SG";
        LocaleId[LocaleId["zh_TW"] = 1028] = "zh_TW";
        LocaleId[LocaleId["co_FR"] = 1155] = "co_FR";
        LocaleId[LocaleId["hr_BA"] = 4122] = "hr_BA";
        LocaleId[LocaleId["hr_HR"] = 1050] = "hr_HR";
        LocaleId[LocaleId["cs_CZ"] = 1029] = "cs_CZ";
        LocaleId[LocaleId["da_DK"] = 1030] = "da_DK";
        LocaleId[LocaleId["prs_AF"] = 1164] = "prs_AF";
        LocaleId[LocaleId["dv_MV"] = 1125] = "dv_MV";
        LocaleId[LocaleId["nl_BE"] = 2067] = "nl_BE";
        LocaleId[LocaleId["nl_NL"] = 1043] = "nl_NL";
        LocaleId[LocaleId["bin_NG"] = 1126] = "bin_NG";
        LocaleId[LocaleId["et_EE"] = 1061] = "et_EE";
        LocaleId[LocaleId["en_AU"] = 3081] = "en_AU";
        LocaleId[LocaleId["en_BZ"] = 10249] = "en_BZ";
        LocaleId[LocaleId["en_CA"] = 4105] = "en_CA";
        LocaleId[LocaleId["en_029"] = 9225] = "en_029";
        LocaleId[LocaleId["en_HK"] = 15369] = "en_HK";
        LocaleId[LocaleId["en_IN"] = 16393] = "en_IN";
        LocaleId[LocaleId["en_ID"] = 14345] = "en_ID";
        LocaleId[LocaleId["en_IE"] = 6153] = "en_IE";
        LocaleId[LocaleId["en_JM"] = 8201] = "en_JM";
        LocaleId[LocaleId["en_MY"] = 17417] = "en_MY";
        LocaleId[LocaleId["en_NZ"] = 5129] = "en_NZ";
        LocaleId[LocaleId["en_PH"] = 13321] = "en_PH";
        LocaleId[LocaleId["en_SG"] = 18441] = "en_SG";
        LocaleId[LocaleId["en_ZA"] = 7177] = "en_ZA";
        LocaleId[LocaleId["en_TT"] = 11273] = "en_TT";
        LocaleId[LocaleId["en_GB"] = 2057] = "en_GB";
        LocaleId[LocaleId["en_US"] = 1033] = "en_US";
        LocaleId[LocaleId["en_ZW"] = 12297] = "en_ZW";
        LocaleId[LocaleId["fo_FO"] = 1080] = "fo_FO";
        LocaleId[LocaleId["fil_PH"] = 1124] = "fil_PH";
        LocaleId[LocaleId["fi_FI"] = 1035] = "fi_FI";
        LocaleId[LocaleId["fr_BE"] = 2060] = "fr_BE";
        LocaleId[LocaleId["fr_CM"] = 11276] = "fr_CM";
        LocaleId[LocaleId["fr_CA"] = 3084] = "fr_CA";
        LocaleId[LocaleId["fr_CD"] = 9228] = "fr_CD";
        LocaleId[LocaleId["fr_CI"] = 12300] = "fr_CI";
        LocaleId[LocaleId["fr_FR"] = 1036] = "fr_FR";
        LocaleId[LocaleId["fr_HT"] = 15372] = "fr_HT";
        LocaleId[LocaleId["fr_LU"] = 5132] = "fr_LU";
        LocaleId[LocaleId["fr_ML"] = 13324] = "fr_ML";
        LocaleId[LocaleId["fr_MC"] = 6156] = "fr_MC";
        LocaleId[LocaleId["fr_MA"] = 14348] = "fr_MA";
        LocaleId[LocaleId["fr_RE"] = 8204] = "fr_RE";
        LocaleId[LocaleId["fr_SN"] = 10252] = "fr_SN";
        LocaleId[LocaleId["fr_CH"] = 4108] = "fr_CH";
        LocaleId[LocaleId["fy_NL"] = 1122] = "fy_NL";
        LocaleId[LocaleId["ff_NG"] = 1127] = "ff_NG";
        LocaleId[LocaleId["gd_GB"] = 1084] = "gd_GB";
        LocaleId[LocaleId["gl_ES"] = 1110] = "gl_ES";
        LocaleId[LocaleId["ka_GE"] = 1079] = "ka_GE";
        LocaleId[LocaleId["de_AT"] = 3079] = "de_AT";
        LocaleId[LocaleId["de_DE"] = 1031] = "de_DE";
        LocaleId[LocaleId["de_LI"] = 5127] = "de_LI";
        LocaleId[LocaleId["de_LU"] = 4103] = "de_LU";
        LocaleId[LocaleId["de_CH"] = 2055] = "de_CH";
        LocaleId[LocaleId["el_GR"] = 1032] = "el_GR";
        LocaleId[LocaleId["gn_PY"] = 1140] = "gn_PY";
        LocaleId[LocaleId["gu_IN"] = 1095] = "gu_IN";
        LocaleId[LocaleId["kl_GL"] = 1135] = "kl_GL";
        LocaleId[LocaleId["ha_Latn_NG"] = 1128] = "ha_Latn_NG";
        LocaleId[LocaleId["haw_US"] = 1141] = "haw_US";
        LocaleId[LocaleId["he_IL"] = 1037] = "he_IL";
        LocaleId[LocaleId["hi_IN"] = 1081] = "hi_IN";
        LocaleId[LocaleId["hu_HU"] = 1038] = "hu_HU";
        LocaleId[LocaleId["ibb_NG"] = 1129] = "ibb_NG";
        LocaleId[LocaleId["is_IS"] = 1039] = "is_IS";
        LocaleId[LocaleId["ig_NG"] = 1136] = "ig_NG";
        LocaleId[LocaleId["id_ID"] = 1057] = "id_ID";
        LocaleId[LocaleId["iu_Latn_CA"] = 2141] = "iu_Latn_CA";
        LocaleId[LocaleId["iu_Cans_CA"] = 1117] = "iu_Cans_CA";
        LocaleId[LocaleId["it_IT"] = 1040] = "it_IT";
        LocaleId[LocaleId["it_CH"] = 2064] = "it_CH";
        LocaleId[LocaleId["ga_IE"] = 2108] = "ga_IE";
        LocaleId[LocaleId["xh_ZA"] = 1076] = "xh_ZA";
        LocaleId[LocaleId["zu_ZA"] = 1077] = "zu_ZA";
        LocaleId[LocaleId["kn_IN"] = 1099] = "kn_IN";
        LocaleId[LocaleId["kr_NG"] = 1137] = "kr_NG";
        LocaleId[LocaleId["ks_Deva"] = 2144] = "ks_Deva";
        LocaleId[LocaleId["ks_Arab"] = 1120] = "ks_Arab";
        LocaleId[LocaleId["kk_KZ"] = 1087] = "kk_KZ";
        LocaleId[LocaleId["km_KH"] = 1107] = "km_KH";
        LocaleId[LocaleId["kok_IN"] = 1111] = "kok_IN";
        LocaleId[LocaleId["ko_KR"] = 1042] = "ko_KR";
        LocaleId[LocaleId["ky_KG"] = 1088] = "ky_KG";
        LocaleId[LocaleId["qut_GT"] = 1158] = "qut_GT";
        LocaleId[LocaleId["rw_RW"] = 1159] = "rw_RW";
        LocaleId[LocaleId["lo_LA"] = 1108] = "lo_LA";
        LocaleId[LocaleId["la_Latn"] = 1142] = "la_Latn";
        LocaleId[LocaleId["lv_LV"] = 1062] = "lv_LV";
        LocaleId[LocaleId["lt_LT"] = 1063] = "lt_LT";
        LocaleId[LocaleId["dsb_DE"] = 2094] = "dsb_DE";
        LocaleId[LocaleId["lb_LU"] = 1134] = "lb_LU";
        LocaleId[LocaleId["mk_MK"] = 1071] = "mk_MK";
        LocaleId[LocaleId["ms_BN"] = 2110] = "ms_BN";
        LocaleId[LocaleId["ms_MY"] = 1086] = "ms_MY";
        LocaleId[LocaleId["ml_IN"] = 1100] = "ml_IN";
        LocaleId[LocaleId["mt_MT"] = 1082] = "mt_MT";
        LocaleId[LocaleId["mni_IN"] = 1112] = "mni_IN";
        LocaleId[LocaleId["mi_NZ"] = 1153] = "mi_NZ";
        LocaleId[LocaleId["mr_IN"] = 1102] = "mr_IN";
        LocaleId[LocaleId["arn_CL"] = 1146] = "arn_CL";
        LocaleId[LocaleId["mn_MN"] = 1104] = "mn_MN";
        LocaleId[LocaleId["mn_Mong_CN"] = 2128] = "mn_Mong_CN";
        LocaleId[LocaleId["ne_NP"] = 1121] = "ne_NP";
        LocaleId[LocaleId["ne_IN"] = 2145] = "ne_IN";
        LocaleId[LocaleId["nb_NO"] = 1044] = "nb_NO";
        LocaleId[LocaleId["nn_NO"] = 2068] = "nn_NO";
        LocaleId[LocaleId["oc_FR"] = 1154] = "oc_FR";
        LocaleId[LocaleId["or_IN"] = 1096] = "or_IN";
        LocaleId[LocaleId["om_Ethi_ET"] = 1138] = "om_Ethi_ET";
        LocaleId[LocaleId["pap_AN"] = 1145] = "pap_AN";
        LocaleId[LocaleId["ps_AF"] = 1123] = "ps_AF";
        LocaleId[LocaleId["fa_IR"] = 1065] = "fa_IR";
        LocaleId[LocaleId["pl_PL"] = 1045] = "pl_PL";
        LocaleId[LocaleId["pt_BR"] = 1046] = "pt_BR";
        LocaleId[LocaleId["pt_PT"] = 2070] = "pt_PT";
        LocaleId[LocaleId["pa_IN"] = 1094] = "pa_IN";
        LocaleId[LocaleId["pa_PK"] = 2118] = "pa_PK";
        LocaleId[LocaleId["quz_BO"] = 1131] = "quz_BO";
        LocaleId[LocaleId["guz_EC"] = 2155] = "guz_EC";
        LocaleId[LocaleId["guz_PE"] = 3179] = "guz_PE";
        LocaleId[LocaleId["ro_RO"] = 1048] = "ro_RO";
        LocaleId[LocaleId["ro_MO"] = 2072] = "ro_MO";
        LocaleId[LocaleId["rm_CH"] = 1047] = "rm_CH";
        LocaleId[LocaleId["ru_RU"] = 1049] = "ru_RU";
        LocaleId[LocaleId["ru_MO"] = 2073] = "ru_MO";
        LocaleId[LocaleId["smn_FI"] = 9275] = "smn_FI";
        LocaleId[LocaleId["smj_NO"] = 4155] = "smj_NO";
        LocaleId[LocaleId["smj_SE"] = 5179] = "smj_SE";
        LocaleId[LocaleId["se_FI"] = 3131] = "se_FI";
        LocaleId[LocaleId["se_NO"] = 1083] = "se_NO";
        LocaleId[LocaleId["se_SE"] = 2107] = "se_SE";
        LocaleId[LocaleId["sms_FI"] = 8251] = "sms_FI";
        LocaleId[LocaleId["sma_NO"] = 6203] = "sma_NO";
        LocaleId[LocaleId["sma_SE"] = 7227] = "sma_SE";
        LocaleId[LocaleId["sa_IN"] = 1103] = "sa_IN";
        LocaleId[LocaleId["sr_Cyrl_BA"] = 7194] = "sr_Cyrl_BA";
        LocaleId[LocaleId["sr_Cyrl_CS"] = 3098] = "sr_Cyrl_CS";
        LocaleId[LocaleId["sr_Latn_BA"] = 6170] = "sr_Latn_BA";
        LocaleId[LocaleId["sr_Latn_CS"] = 2074] = "sr_Latn_CS";
        LocaleId[LocaleId["nso_ZA"] = 1132] = "nso_ZA";
        LocaleId[LocaleId["tn_ZA"] = 1074] = "tn_ZA";
        LocaleId[LocaleId["sd_Arab_PK"] = 2137] = "sd_Arab_PK";
        LocaleId[LocaleId["sd_Deva_IN"] = 1113] = "sd_Deva_IN";
        LocaleId[LocaleId["si_LK"] = 1115] = "si_LK";
        LocaleId[LocaleId["sk_SK"] = 1051] = "sk_SK";
        LocaleId[LocaleId["sl_SI"] = 1060] = "sl_SI";
        LocaleId[LocaleId["so_SO"] = 1143] = "so_SO";
        LocaleId[LocaleId["es_AR"] = 11274] = "es_AR";
        LocaleId[LocaleId["es_BO"] = 16394] = "es_BO";
        LocaleId[LocaleId["es_CL"] = 13322] = "es_CL";
        LocaleId[LocaleId["es_CO"] = 9226] = "es_CO";
        LocaleId[LocaleId["es_CR"] = 5130] = "es_CR";
        LocaleId[LocaleId["es_DO"] = 7178] = "es_DO";
        LocaleId[LocaleId["es_EC"] = 12298] = "es_EC";
        LocaleId[LocaleId["es_SV"] = 17418] = "es_SV";
        LocaleId[LocaleId["es_GT"] = 4106] = "es_GT";
        LocaleId[LocaleId["es_HN"] = 18442] = "es_HN";
        LocaleId[LocaleId["es_MX"] = 2058] = "es_MX";
        LocaleId[LocaleId["es_NI"] = 19466] = "es_NI";
        LocaleId[LocaleId["es_PA"] = 6154] = "es_PA";
        LocaleId[LocaleId["es_PY"] = 15370] = "es_PY";
        LocaleId[LocaleId["es_PE"] = 10250] = "es_PE";
        LocaleId[LocaleId["es_PR"] = 20490] = "es_PR";
        LocaleId[LocaleId["es_ES"] = 3082] = "es_ES";
        LocaleId[LocaleId["es_ES_tradnl"] = 1034] = "es_ES_tradnl";
        LocaleId[LocaleId["es_US"] = 21514] = "es_US";
        LocaleId[LocaleId["es_UY"] = 14346] = "es_UY";
        LocaleId[LocaleId["es_VE"] = 8202] = "es_VE";
        LocaleId[LocaleId["st_ZA"] = 1072] = "st_ZA";
        LocaleId[LocaleId["sw_KE"] = 1089] = "sw_KE";
        LocaleId[LocaleId["sv_FI"] = 2077] = "sv_FI";
        LocaleId[LocaleId["sv_SE"] = 1053] = "sv_SE";
        LocaleId[LocaleId["syr_SY"] = 1114] = "syr_SY";
        LocaleId[LocaleId["tg_Cyrl_TJ"] = 1064] = "tg_Cyrl_TJ";
        LocaleId[LocaleId["tzm_Arab_MA"] = 1119] = "tzm_Arab_MA";
        LocaleId[LocaleId["tzm_Latn_DZ"] = 2143] = "tzm_Latn_DZ";
        LocaleId[LocaleId["ta_IN"] = 1097] = "ta_IN";
        LocaleId[LocaleId["tt_RU"] = 1092] = "tt_RU";
        LocaleId[LocaleId["te_IN"] = 1098] = "te_IN";
        LocaleId[LocaleId["th_TH"] = 1054] = "th_TH";
        LocaleId[LocaleId["bo_CN"] = 1105] = "bo_CN";
        LocaleId[LocaleId["ti_ER"] = 2163] = "ti_ER";
        LocaleId[LocaleId["ti_ET"] = 1139] = "ti_ET";
        LocaleId[LocaleId["ts_ZA"] = 1073] = "ts_ZA";
        LocaleId[LocaleId["tr_TR"] = 1055] = "tr_TR";
        LocaleId[LocaleId["tk_TM"] = 1090] = "tk_TM";
        LocaleId[LocaleId["ug_CN"] = 1152] = "ug_CN";
        LocaleId[LocaleId["uk_UA"] = 1058] = "uk_UA";
        LocaleId[LocaleId["hsb_DE"] = 1070] = "hsb_DE";
        LocaleId[LocaleId["ur_PK"] = 1056] = "ur_PK";
        LocaleId[LocaleId["uz_Cyrl_UZ"] = 2115] = "uz_Cyrl_UZ";
        LocaleId[LocaleId["uz_Latn_UZ"] = 1091] = "uz_Latn_UZ";
        LocaleId[LocaleId["ve_ZA"] = 1075] = "ve_ZA";
        LocaleId[LocaleId["vi_VN"] = 1066] = "vi_VN";
        LocaleId[LocaleId["cy_GB"] = 1106] = "cy_GB";
        LocaleId[LocaleId["wo_SN"] = 1160] = "wo_SN";
        LocaleId[LocaleId["sah_RU"] = 1157] = "sah_RU";
        LocaleId[LocaleId["ii_CN"] = 1144] = "ii_CN";
        LocaleId[LocaleId["yi_Hebr"] = 1085] = "yi_Hebr";
        LocaleId[LocaleId["yo_NG"] = 1130] = "yo_NG";
        LocaleId[LocaleId["ja_JP"] = 1041] = "ja_JP";
    })(LocaleId = exports.LocaleId || (exports.LocaleId = {}));
    var SectionBreakType;
    (function (SectionBreakType) {
        SectionBreakType[SectionBreakType["EvenPage"] = 'EvenPage'] = "EvenPage";
        SectionBreakType[SectionBreakType["NewPage"] = 'NewPage'] = "NewPage";
        SectionBreakType[SectionBreakType["Continuous"] = 'NoBreak'] = "Continuous";
        SectionBreakType[SectionBreakType["OddPage"] = 'OddPage'] = "OddPage";
    })(SectionBreakType = exports.SectionBreakType || (exports.SectionBreakType = {}));
    exports.CONTROL_CHARACTERS = {
        'Tab': '\t',
        'Paragraph': '\n',
        'LineBreak': '\v',
        'PageBreak': '\f',
        'ColumnBreak': '\u000e',
        'Image': '\u0011',
        "Table": "\u0012",
        "Row": "\u0013",
        "Cell": "\u0014",
        "Marker_Start": "\u0015",
        "Marker_End": "\u0016",
        "Field_Separator": "\u0017",
        "Section_Break": "\u0018",
    };
});
