define(["require", "exports", "../../src/document-editor/document-editor", "@syncfusion/ej2-base", "../../src/index", "../../src/index", "../../src/document-editor/implementation/editor-history/index", "../test-helper.spec"], function (require, exports, document_editor_1, ej2_base_1, index_1, index_2, index_3, test_helper_spec_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    describe('Selection headerFooter format link to previous selection, editing and history validation', function () {
        var editor;
        var documentHelper;
        beforeAll(function () {
            var ele = ej2_base_1.createElement('div', { id: 'container', styles: 'width:100%;height:500px' });
            document.body.innerHTML = '';
            document.body.appendChild(ele);
            document_editor_1.DocumentEditor.Inject(index_1.Editor, index_3.EditorHistory, index_2.Selection);
            editor = new document_editor_1.DocumentEditor({ enableEditor: true, isReadOnly: false, enableSelection: true, enableEditorHistory: true });
            editor.acceptTab = true;
            editor.documentHelper.containerCanvasIn = test_helper_spec_1.TestHelper.containerCanvas;
            editor.documentHelper.selectionCanvasIn = test_helper_spec_1.TestHelper.selectionCanvas;
            editor.documentHelper.render.pageCanvasIn = test_helper_spec_1.TestHelper.pageCanvas;
            editor.documentHelper.render.selectionCanvasIn = test_helper_spec_1.TestHelper.pageSelectionCanvas;
            editor.appendTo('#container');
            documentHelper = editor.documentHelper;
            editor.editor.insertText('Hello world');
        });
        afterAll(function (done) {
            editor.destroy();
            document.body.removeChild(document.getElementById('container'));
            editor = undefined;
            documentHelper = undefined;
            document.body.innerHTML = '';
            setTimeout(function () {
                done();
            }, 1000);
        });
        it('Simple document with page break', function () {
            console.log('Simple document with page break');
            editor.openBlank();
            editor.editor.insertPageBreak();
            editor.editor.insertPageBreak();
            editor.selection.goToPage(1);
            editor.selection.goToHeader();
            expect(editor.selection.sectionFormat.oddPageHeader.linkToPrevious).toBe(false);
            editor.selection.goToFooter();
            expect(editor.selection.sectionFormat.oddPageFooter.linkToPrevious).toBe(false);
            editor.selection.goToPage(2);
            editor.selection.goToHeader();
            expect(editor.selection.sectionFormat.oddPageHeader.linkToPrevious).toBe(false);
            editor.selection.goToFooter();
            expect(editor.selection.sectionFormat.oddPageFooter.linkToPrevious).toBe(false);
            editor.selection.goToPage(3);
            editor.selection.goToHeader();
            expect(editor.selection.sectionFormat.oddPageHeader.linkToPrevious).toBe(false);
            editor.selection.goToFooter();
            expect(editor.selection.sectionFormat.oddPageFooter.linkToPrevious).toBe(false);
            editor.selection.goToPage(1);
            editor.selection.goToHeader();
            editor.editor.insertText("HeaderText");
            editor.selection.goToFooter();
            editor.editor.insertText("FooterText");
            editor.selection.goToPage(2);
            editor.selection.goToHeader();
            expect(editor.selection.start.currentWidget.children[0].text).toBe("HeaderText");
            editor.selection.goToFooter();
            expect(editor.selection.start.currentWidget.children[0].text).toBe("FooterText");
            editor.selection.goToPage(3);
            editor.selection.goToHeader();
            expect(editor.selection.start.currentWidget.children[0].text).toBe("HeaderText");
            editor.selection.goToFooter();
            expect(editor.selection.start.currentWidget.children[0].text).toBe("FooterText");
        });
        it('Document with multiple section', function () {
            console.log('Document with multiple section');
            editor.openBlank();
            editor.editor.insertSectionBreak();
            editor.editor.insertSectionBreak();
            editor.selection.goToPage(1);
            editor.selection.goToHeader();
            expect(editor.selection.sectionFormat.oddPageHeader.linkToPrevious).toBe(false);
            editor.selection.goToFooter();
            expect(editor.selection.sectionFormat.oddPageFooter.linkToPrevious).toBe(false);
            editor.selection.goToPage(2);
            editor.selection.goToHeader();
            expect(editor.selection.sectionFormat.oddPageHeader.linkToPrevious).toBe(true);
            editor.selection.goToFooter();
            expect(editor.selection.sectionFormat.oddPageFooter.linkToPrevious).toBe(true);
            editor.selection.goToPage(3);
            editor.selection.goToHeader();
            expect(editor.selection.sectionFormat.oddPageHeader.linkToPrevious).toBe(true);
            editor.selection.goToFooter();
            expect(editor.selection.sectionFormat.oddPageFooter.linkToPrevious).toBe(true);
            editor.selection.goToPage(1);
            editor.selection.goToHeader();
            editor.editor.insertText("HeaderText");
            editor.selection.goToFooter();
            editor.editor.insertText("FooterText");
            editor.selection.goToPage(2);
            editor.selection.goToHeader();
            expect(editor.selection.start.currentWidget.children[0].text).toBe("HeaderText");
            editor.selection.goToFooter();
            expect(editor.selection.start.currentWidget.children[0].text).toBe("FooterText");
            editor.selection.goToPage(3);
            editor.selection.goToHeader();
            expect(editor.selection.start.currentWidget.children[0].text).toBe("HeaderText");
            editor.selection.goToFooter();
            expect(editor.selection.start.currentWidget.children[0].text).toBe("FooterText");
            editor.selection.goToPage(2);
            editor.selection.goToHeader();
            editor.selection.sectionFormat.oddPageHeader.linkToPrevious = false;
            editor.editor.insertText("LP OFF ");
            editor.selection.goToFooter();
            editor.selection.sectionFormat.oddPageFooter.linkToPrevious = false;
            editor.editor.insertText("LP OFF ");
            editor.selection.goToPage(3);
            editor.selection.goToHeader();
            expect(editor.selection.sectionFormat.oddPageHeader.linkToPrevious).toBe(true);
            expect(editor.selection.start.currentWidget.children[0].text).toBe("LP OFF HeaderText");
            editor.selection.goToFooter();
            expect(editor.selection.sectionFormat.oddPageFooter.linkToPrevious).toBe(true);
            expect(editor.selection.start.currentWidget.children[0].text).toBe("LP OFF FooterText");
            editor.selection.goToPage(1);
            editor.selection.goToHeader();
            expect(editor.selection.start.currentWidget.children[0].text).toBe("HeaderText");
            editor.selection.goToFooter();
            expect(editor.selection.start.currentWidget.children[0].text).toBe("FooterText");
            var i = 0;
            while (i < 4) {
                editor.editorHistory.undo();
                i++;
            }
            editor.selection.goToPage(3);
            editor.selection.goToHeader();
            expect(editor.selection.sectionFormat.oddPageHeader.linkToPrevious).toBe(true);
            expect(editor.selection.start.currentWidget.children[0].text).toBe("HeaderText");
            editor.selection.goToFooter();
            expect(editor.selection.sectionFormat.oddPageFooter.linkToPrevious).toBe(true);
            expect(editor.selection.start.currentWidget.children[0].text).toBe("FooterText");
            editor.selection.goToPage(2);
            editor.selection.goToHeader();
            expect(editor.selection.sectionFormat.oddPageHeader.linkToPrevious).toBe(true);
            expect(editor.selection.start.currentWidget.children[0].text).toBe("HeaderText");
            editor.selection.goToFooter();
            expect(editor.selection.sectionFormat.oddPageFooter.linkToPrevious).toBe(true);
            expect(editor.selection.start.currentWidget.children[0].text).toBe("FooterText");
            var j = 0;
            while (j < 4) {
                editor.editorHistory.redo();
                j++;
            }
            editor.selection.goToPage(2);
            editor.selection.goToHeader();
            expect(editor.selection.sectionFormat.oddPageHeader.linkToPrevious).toBe(false);
            editor.selection.selectAll();
            expect(editor.selection.text).toBe("LP OFF HeaderText\r");
            editor.selection.goToFooter();
            expect(editor.selection.sectionFormat.oddPageFooter.linkToPrevious).toBe(false);
            editor.selection.selectAll();
            expect(editor.selection.text).toBe("LP OFF FooterText\r");
            editor.selection.goToPage(3);
            editor.selection.goToHeader();
            expect(editor.selection.sectionFormat.oddPageHeader.linkToPrevious).toBe(true);
            editor.selection.selectAll();
            expect(editor.selection.text).toBe("LP OFF HeaderText\r");
            editor.selection.goToFooter();
            expect(editor.selection.sectionFormat.oddPageFooter.linkToPrevious).toBe(true);
            editor.selection.selectAll();
            expect(editor.selection.text).toBe("LP OFF FooterText\r");
        });
    });
});
